const EVENT_TYPES = {
  NEW_DELIVERY_REQUEST: {
    from_server: 'NEW_DELIVERY_REQUEST_FROM_SERVER',
    to_client: 'NEW_DELIVERY_REQUEST_TO_CLIENT',
  },
  // DELIVERY_STATUS_UPDATE: 'DELIVERY_STATUS_UPDATE',
  // PAYMENT_UPDATE: 'PAYMENT_UPDATE',
};

module.exports = { EVENT_TYPES };
